### ISSUE TITLE
Form submission popup  Added Featured 

### ISSUE THREAD

**Issue by Che140401** [AbhiPatel10/openzone#104]
### Description

Form submission required 

**No form submission**

https://github.com/AbhiPatel10/openzone/assets/109230049/9e81e659-8a11-405a-bd4a-8148b829f228

**Form submission**

https://github.com/AbhiPatel10/openzone/assets/109230049/df216f9c-06ba-484a-82f9-e2018a56512a

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by AbhiPatel10** [comment]
This Popup feature not looks good. We will implement toaster for success and error. While implementing an api.
