### ISSUE TITLE
[Feature] Contact us form needs to fix in mobile view 

### ISSUE THREAD

**Issue by kapilG0** [AbhiPatel10/openzone#106]
### Description

Contact us form alignment needs to be done in mobile view 
![Screenshot_20240520_215923](https://github.com/AbhiPatel10/openzone/assets/59639410/1f6ebef1-bc57-41c4-bf9a-879cb0327be2)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kapilG0** [comment]
Hello @AbhiPatel10 please assign this issue to me under gssoc 24

**Comment by AbhiPatel10** [comment]
This issue is already open, so closing this one
