### ISSUE TITLE
Adding the Animations to the website

### ISSUE THREAD

**Issue by suraj-9849** [AbhiPatel10/openzone#107]
### Description

So on exploring this website I saw there were no animations so I thought of adding the animations to the website which can enhance the user experience 

I would like to work on this . please assign this to me under @gssoc @AbhiPatel10  I will be using the GSAP for the animations

- [X] I agree to follow this project's Code of Conduct

**Comment by AbhiPatel10** [comment]
Currently there is no more content in this website so adding animation is not worthy....
