### ISSUE TITLE
[BUG] Fixing Navbar alignment! 

### ISSUE THREAD

**Issue by Ratangulati** [AbhiPatel10/openzone#119]
### What would you like to share or ask?

<img width="706" alt="Screenshot 2024-05-22 at 12 29 58 PM" src="https://github.com/AbhiPatel10/openzone/assets/116749593/496e78b0-0d02-45d4-b3f9-775a3a6e4916">

I plan to correct the UI for the header as the buttons are touching the page component.

### Additional information

 - [x] I agree to follow this project's Code of Conduct
 - [x] I am a contributor for GSSOC 2024

**Comment by ParthNakum21** [comment]
Hello, I'm interested in contributing to the project by aligning the UI components. Could you please assign this task to me under GSSoC with appropriate level?

**Comment by AbhiPatel10** [comment]
Already solved this Issue.
