### ISSUE TITLE
[OTHER] [UI] Alignment in Footer Section

### ISSUE THREAD

**Issue by Ratangulati** [AbhiPatel10/openzone#120]
### What would you like to share or ask?

<img width="1430" alt="Screenshot 2024-05-22 at 12 41 12 PM" src="https://github.com/AbhiPatel10/openzone/assets/116749593/046ca222-38c7-4fa0-a126-5d805fe57dd2">

The Open Zone and quick links are not aligned properly, The Open Zone container is not equal to the open link container. I plan to make them top of both of them equal on x-axis.

### Additional information

 - [x] I agree to follow this project's Code of Conduct
 - [x] I am a contributor for GSSOC 2024

**Comment by Piyush-linux** [comment]
This issue has already been resolved :+1:
