### ISSUE TITLE
[Feature]: implement CodeQL workflow for `TypeScript`

### ISSUE THREAD

**Issue by harmeetsingh11** [AbhiPatel10/openzone#123]
### Description

The repository contains code in `TypeScript` , it does not have workflow for code scanning. 

### How would you like to see it implemented?

I propose integrating a CodeQL workflow to automate security checks. Leveraging GitHub's code analysis engine, CodeQL will detect vulnerabilities within the codebase and report them as code scanning alerts. This workflow will be triggered automatically for every push, commit, and pull request via GitHub Actions.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing issues
- [X] I am a GSSoC'24 contributor

**Comment by AbhiPatel10** [comment]
@harmeetsingh11 Assigning to you, go ahead
