### ISSUE TITLE
[OTHER] - Footer is not responsive and Footer UI enhancement.

### ISSUE THREAD

**Issue by NilanchalaPanda** [AbhiPatel10/openzone#19]
### What would you like to share or ask?

The footer of OpenZone is not optimized for Mobile Version and also in Desktop version the design is to be enhanced.

I would love to contribute on this project and work as a GSSoC'24 Contributor. Looking forward for your response to assign the issue to me 🙌🏻

IMAGES :
![image](https://github.com/AbhiPatel10/openzone/assets/110488337/316d2c58-d1c6-41a1-92d2-4757a8c7dcd8)
![image](https://github.com/AbhiPatel10/openzone/assets/110488337/32025e37-79a9-409c-a722-b458258e8420)

**Comment by Azhar-0401** [comment]
i would like to resolve the issue ,kindly assign the issue to me under GGSOC'24 tag

**Comment by AbhiPatel10** [comment]
Someone Already Worked on this issue. Thank you so much for you issue. 

Please Find another issue in this project.
