### ISSUE TITLE
[Feature] Update Footer Design

### ISSUE THREAD

**Issue by AbhiPatel10** [AbhiPatel10/openzone#2]
### Description

Update Footer Design, please make sure use Shadcn + tailwind css for design

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Prithwi32** [comment]
@AbhiPatel10 I would like to work on this issue under GSSoC'24,
Please could you assign me

**Comment by shirkocurek** [comment]
Please assign this issue to me. Thanks

**Comment by bhavya-dang** [comment]
I have experience with both shadcn and tailwind. Please assign this issue to me.

**Comment by AbhiPatel10** [comment]
> @AbhiPatel10 I would like to work on this issue under GSSoC'24,
> Please could you assign me
> 

Go Ahead @Prithwi32 , Assigning to you. 

Let me know if you need any help.

**Comment by Prithwi32** [comment]
@AbhiPatel10 Made PR
