### ISSUE TITLE
[OTHER] Content in the grid isn't responsive

### ISSUE THREAD

**Issue by Ankitapanda25** [AbhiPatel10/openzone#20]
### What would you like to share or ask?

<img width="487" alt="gssoc" src="https://github.com/AbhiPatel10/openzone/assets/123666302/9e45f6fe-0e59-4e5b-9b6b-799bd278a50c">

The content here overflows each grid container and isnt responsive for tablet and mobile view

Please allow me to work on this issue under GSSOC 2024.

**Comment by Aadityagoel15** [comment]
Hey @AbhiPatel10 
I also want to work on this issue under GSSOC 2024.

**Comment by AbhiPatel10** [comment]
@Ankitapanda25  Please go ahead on this issue.

Please let me know if you need any help.

Sorry @Aadityagoel15, Here we assign issue as First come first serve.
