### ISSUE TITLE
Login and signup feature

### ISSUE THREAD

**Issue by Vishnu1804K** [AbhiPatel10/openzone#21]
### Description

I want to implement login and signup feature so that the website work dynamically please assign me this issue under gssoc'24

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by spywolf2049** [comment]
I am willing to work on this because i have experience in creating such websites. Please assign me this under GSSOC'24.

**Comment by Vishnu1804K** [comment]
hey @spywolf2049  it is my issue you raise your own issue

**Comment by AbhiPatel10** [comment]
We have already implemented login with Github so there is no need to implement Other login features.
