### ISSUE TITLE
[Feature] Dark Mode

### ISSUE THREAD

**Issue by notsoocool** [AbhiPatel10/openzone#22]
## Dark Mode Addition Request

**Description:**
The website currently lacks a dark mode feature, which can enhance user experience, particularly for users who prefer darker interfaces or need to reduce eye strain in low-light conditions. This issue proposes adding a dark mode option to the website.

**Rationale:**
Implementing a dark mode feature can provide users with more control over their browsing experience and make the website more accessible to a wider audience. Dark mode is increasingly becoming a standard feature in web applications and websites, and its absence could be a limitation for users who rely on it.

**Implementation Considerations:**
Consider the technical aspects of implementing dark mode on the website. This may involve updating CSS stylesheets to accommodate dark mode, adding a toggle switch or button to enable/disable dark mode, and ensuring compatibility with different browsers and devices.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by notsoocool** [comment]
@AbhiPatel10 can you assign me this issue under GSSOC 2024

**Comment by Ashutosh-0506** [comment]
Hey there! I'm Ashutosh Kumar, a full-stack MERN web developer. With experience in numerous successful MERN stack  projects, I excel in  HTML, CSS,JavaScript,C, C++,jQuery, Node.js, React.js, Bootstrap, Tailwind, Express, MongoDB, API,GraphQL,WebRTC. 
You can find me on LinkedIn : https://www.linkedin.com/in/ashutosh-kumar-60b262251/ 
 GitHub : https://github.com/Ashutosh-0506. 
Looking forward to contributing to GSSOC 2024!

**Comment by AbhiPatel10** [comment]
Sorry @notsoocool, I'm not planning to add Dark mode in this project.
