### ISSUE TITLE
[OTHER] Add Contact Us Page

### ISSUE THREAD

**Issue by komal-agarwal5** [AbhiPatel10/openzone#23]
### What would you like to share or ask?

In navbar there is a field for contact us but it does not redirect to any page.Hence I would like to create a contact us page wherein the contact details will be provided and a form can be included using formspree for contacting via any message 

### Additional information

![open zone](https://github.com/AbhiPatel10/openzone/assets/122633300/06584c00-c417-4303-bcfb-cda97a8d430d)
Here the Contact Us option is seen but a page for the same isn't available, hence I am raising this issue. Please assign me this under GSSoC'24.
Thank you!

**Comment by riyasaxena32** [comment]
please assign this issue to me

**Comment by Vibhuti270** [comment]
Please assign this issue to me.

**Comment by Karankumar2004** [comment]
Hey @AbhiPatel10 , I'm keen to contribute. Could you assign me this issue under GSSoc 24'?

**Comment by AbhiPatel10** [comment]
@komal-agarwal5 , Go ahead

Please create only form design using TailwindCSS. and do not use formspree as in free plan we only get 50 submissions. so We can't use it. we will implement back end in node.js to connect this form later on.

**Comment by komal-agarwal5** [comment]
@AbhiPatel10 Ok understood
