### ISSUE TITLE
Regarding the twitter logo

### ISSUE THREAD

**Issue by am-1145** [AbhiPatel10/openzone#27]
### Description

Hi, @AbhiPatel10  The twitter logo is not updated in the footer section. I want to work on that. Please assign me this issue.
Thanks

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Ashutosh-0506** [comment]
Hey there! I'm Ashutosh Kumar, a full-stack MERN web developer. With experience in numerous successful MERN stack  projects, I excel in  HTML, CSS,JavaScript,C, C++,jQuery, Node.js, React.js, Bootstrap, Tailwind, Express, MongoDB, API,GraphQL,WebRTC. 
You can find me on LinkedIn : https://www.linkedin.com/in/ashutosh-kumar-60b262251/ 
 GitHub : https://github.com/Ashutosh-0506. 
Looking forward to contributing to GSSOC 2024!
