### ISSUE TITLE
[Feature] <description> Get Started button on Home page is not working

### ISSUE THREAD

**Issue by iamtanmay07** [AbhiPatel10/openzone#29]
### Description

The Button on the landing page that is "Get Started" is not working 
Need to add some path on clicking that

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by SandipGyawali** [comment]
@iamtanmay07 is this get started button were you talking about 

![image](https://github.com/AbhiPatel10/openzone/assets/66510112/85589ef6-e509-4ee8-9505-03e9025d2609)

if yes then can you explain in detail i want to contribute to it

**Comment by iamtanmay07** [comment]
> @iamtanmay07 is this get started button were you talking about
> 
> ![image](https://private-user-images.githubusercontent.com/66510112/329782595-85589ef6-e509-4ee8-9505-03e9025d2609.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU0NTkyODcsIm5iZiI6MTcxNTQ1ODk4NywicGF0aCI6Ii82NjUxMDExMi8zMjk3ODI1OTUtODU1ODllZjYtZTUwOS00ZWU4LTk1MDUtMDNlOTAyNWQyNjA5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTExVDIwMjMwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRkMzI2MTdlYmNhNjQxZDllZmQ5MzQyMGZhNDgxNWRiYmRhMTEzYTU2MmEwNDdhZWIwNzYxNWE0YThjNmUwZjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.YsZv5pbKZL9aqnxJKEq0AcX1hep3-xGPYC7GVjX_ogE)
> 
> if yes then can you explain in detail i want to contribute to it

yeah but it was fixed !

**Comment by Latish705** [comment]
@iamtanmay07 its not working now also
