### ISSUE TITLE
[Feature] <dark theme mode on of>

### ISSUE THREAD

**Issue by riyasaxena32** [AbhiPatel10/openzone#30]
### Description

add dark theme on or off button..it make ui more impressive.
iI have already implement it in many project.kindly assign me this issue

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by M-ayank2005** [comment]
Adding dark theme option makes user experience more impressive .kindly assign me this issue.

**Comment by Ashutosh-0506** [comment]
Hey there! I'm Ashutosh Kumar, a full-stack MERN web developer. With experience in numerous successful MERN stack  projects, I excel in  HTML, CSS,JavaScript,C, C++,jQuery, Node.js, React.js, Bootstrap, Tailwind, Express, MongoDB, API,GraphQL,WebRTC. 
You can find me on LinkedIn : https://www.linkedin.com/in/ashutosh-kumar-60b262251/ 
 GitHub : https://github.com/Ashutosh-0506. 
Looking forward to contributing to GSSOC 2024!
