### ISSUE TITLE
[Feature] Google login

### ISSUE THREAD

**Issue by nagamukesh** [AbhiPatel10/openzone#32]
### Description

As there is an option to login/register using github, one can also login using google
I can add this feature where I can use google sign-in API 
please assign me this issue under gssoc 2024

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by spywolf2049** [comment]
I am willing to work on this because i have experience in creating such websites. Please assign me this under GSSOC'24.
