### ISSUE TITLE
[Design Issue ] Communities and footer collapsing with each other .

### ISSUE THREAD

**Issue by Ayushmaanagarwal1211** [AbhiPatel10/openzone#34]
### What would you like to share or ask?

At the bottom of the page the communities tab is colliding with the  footer . Their is some design issue .
![Screenshot 2024-05-12 095743](https://github.com/AbhiPatel10/openzone/assets/118350936/b70d7d1d-0c94-4308-aa79-070d36675808)
If found it correct i want to work on that under GSSOC'24

**Comment by Karankumar2004** [comment]
Hey @AbhiPatel10, as I have expertise in frontend development and UI/UX design, I'd like to address this issue. Could you please assign it to me under GSSoc 24'?

**Comment by AbhiPatel10** [comment]
This issue has been solved, 

Please find another Issue, and thank you so much for your interest in contributing this project.
