### ISSUE TITLE
Login and SignUp Page and Authentication With NextJs

### ISSUE THREAD

**Issue by Rohitha-pudu** [AbhiPatel10/openzone#35]
### Full Login and SignUp Authentication
There is no login and sign up pages 

- I will create both login and signup pages along with authentication Using Next
- I will work on this issue.Please assign this issue to me
- GSSOC24

**Comment by Piyush5784** [comment]
I will create a Login and Signup page with Google and GitHub authentication using NextAuth.
Please assign this issue to me under GSSOC 24

**Comment by AbhiPatel10** [comment]
I'm not planning to make new page for login and signup page for authentication as we need user GitHub details. so we have only used GitHub authentication for sign in and Signup
