### ISSUE TITLE
Under the projects section all projects not having clickable link

### ISSUE THREAD

**Issue by Nehakumari1208** [AbhiPatel10/openzone#39]
will make the clickable links and also the copying into clipboard functionality.Assign this issue to me

**Comment by Azhar-0401** [comment]
i would like to resolve the issue ,kindly assign the issue to me under GGSOC'24 tag

**Comment by AbhiPatel10** [comment]
Some one already working on this issue, please find Another issue in this project and thank you so much for your interest in this project.
