### ISSUE TITLE
[OTHER] : [Bug] Star Appears on Small Screens for Opening Menu in Navbar

### ISSUE THREAD

**Issue by bro-maanii** [AbhiPatel10/openzone#41]
I have marked the issue 

![image](https://github.com/AbhiPatel10/openzone/assets/125199246/b815b629-1109-43d3-9c4e-fe6a8ec30f3d)

### Instead of this star (*) there should be Menu Icon for good user experience

**Comment by AbhiPatel10** [comment]
@bro-maanii Assigning this issue to you.

**Comment by bro-maanii** [comment]
> @bro-maanii Assigning this issue to you. 

Thank you
