### ISSUE TITLE
Add Icons on the navbar

### ISSUE THREAD

**Issue by harshmishra19** [AbhiPatel10/openzone#42]
### Description

- The current navbar lacks icons, which impacts its visual appeal and usability. Users might find it less engaging and intuitive to navigate through the website without visual cues provided by icons.
- I propose adding respective icons to the navbar to enhance its visual appeal and improve user navigation experience. These icons will align with the theme of the website and provide users with clear visual cues for each navigation option

### Screenshots

![Screenshot 2024-05-11 080754](https://github.com/AbhiPatel10/openzone/assets/115486960/0757e561-effa-483c-bb93-052f9229608a)
![Screenshot 2024-05-12 083752](https://github.com/AbhiPatel10/openzone/assets/115486960/aefaafd3-c5b3-4bea-9669-b04e4adb5f43)

### Additional Information

Could you plz assign this issue to me under GSSOC24

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Karankumar2004** [comment]
Hey @AbhiPatel10 , I'm keen to contribute. Could you assign me this issue under GSSoc 24'?

**Comment by shirkocurek** [comment]
Happy to do this one as well! Please assign

**Comment by AbhiPatel10** [comment]
Well i'm not planning to add icons in navbar. Sorry about that.

Please find another issue in this project.
