### ISSUE TITLE
[UI] : Footer enhancement

### ISSUE THREAD

**Issue by SaranshBangar** [AbhiPatel10/openzone#45]
### What would you like to share or ask?

Adding actual links and proper text to the footer can enhance UX

Current footer->
![image](https://github.com/AbhiPatel10/openzone/assets/114401238/b74f5124-5276-40d0-8497-470594c198cc)

### Additional information

I am a GSSoC contributor, please label this issue accordingly

**Comment by Azhar-0401** [comment]
i would like to resolve the issue ,kindly assign the issue to me under GGSOC'24 tag

**Comment by SaranshBangar** [comment]
> i would like to resolve the issue ,kindly assign the issue to me under GGSOC'24 tag

I am already working on it @Azhar-0401

**Comment by SaranshBangar** [comment]
Resolved in PR #53
