### ISSUE TITLE
[Feature] Dark/ Light theme toggle Feature

### ISSUE THREAD

**Issue by mohdjami** [AbhiPatel10/openzone#61]
### Description

I want to add a dark/light theme toggle button for the application by which users can switch between themes.

### Screenshots

Similar to this that I implemented in one of my projects.

https://github.com/AbhiPatel10/openzone/assets/114595881/6edd0ecc-567e-4b28-9841-5d1d14cd1838.

### Additional Information

I have to also create a dark theme for the application after implementing the toggle button seperately.

Approach: I will use inbuilt next-theme to add this feature.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mohdjami** [comment]
Label the issue under GSSoC'24 and assign it to me so that I can start working on it.

**Comment by AdhithiManjunath** [comment]
i would want to work on this as issue , as i have experience in UI/UX and designing too . please allocate this issue so that i can contribute

**Comment by AbhiPatel10** [comment]
This features is not needed for this project. Thanks for efforts.
