### ISSUE TITLE
Feature : Add Code_of_Conduct.md  , Contributing.md , Issue_guidelines.md  , enhance Readme.md

### ISSUE THREAD

**Issue by aasthakourav20** [AbhiPatel10/openzone#71]
### Description

What's missing in this repository !!

 - Code of Conduct
A Code of Conduct is crucial for maintaining a respectful and inclusive community. It sets clear expectations for behavior and outlines the steps for reporting and addressing unacceptable behavior. Here’s why it’s important:

Sets Behavioral Expectations: It clearly defines acceptable and unacceptable behavior, helping to create a welcoming and inclusive environment for all participants.
Promotes Respect and Inclusivity: It encourages respect and inclusivity, ensuring that everyone feels safe and valued within the community.

 - Contributing File
The Contributing file provides guidelines for how to contribute to the project. This includes everything from coding standards and style guides to how to submit pull requests and report issues. Here’s why it’s essential:

Encourages Contributions: It provides clear instructions on how to get involved, making it easier for newcomers to start contributing.
Maintains Quality: It sets standards for contributions, ensuring that new code and documentation meet the project's quality requirements.

Kindly assign this issue to me under GSSoC'24 . 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by AbhiPatel10** [comment]
Assigning to you @aasthakourav20 

This Files are important for this project. please note that this files should help to contribute this project. use proper guide as per this project.

**Comment by aasthakourav20** [comment]
> Assigning to you @aasthakourav20
> 
> This Files are important for this project. please note that this files should help to contribute this project. use proper guide as per this project.
Hey @AbhiPatel10 , will keep all these points in my mind . Contributing file is already there so I'm going ahead with other necessary files.Thank you
