### ISSUE TITLE
[Feature] Add "About us" Page to Website

### ISSUE THREAD

**Issue by MastanSayyad** [AbhiPatel10/openzone#75]
### Description

Hi @AbhiPatel10 
Adding an About Us page would provide valuable context and information to users visiting the platform.

Currently, OpenZone serves as a platform for discovering and contributing to open-source projects, but it lacks an About Us page where users can learn more about the platform

### Additional Information

could you please assign this issue to me under GSSOC 24, so that I can start working on it?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by AbhiPatel10** [comment]
About us page is not needed for this project. Thanks for your contribution

**Comment by MastanSayyad** [comment]
Thank you for letting me know @AbhiPatel10, I will look for some other issues, do let me know if you have anything under your plans.
