### ISSUE TITLE
[Feature] : Navigate Github

### ISSUE THREAD

**Issue by sivaprasath2004** [AbhiPatel10/openzone#76]
### Description

- In the project page i will search `social-media-application` There is can be lot of projects show .
- If the project will be click direct Navigate to the `Github` user project page.
- It user easy to contact and `connect` to the project section

### Screenshots

![Screenshot from 2024-05-17 12-46-56](https://github.com/AbhiPatel10/openzone/assets/121082414/28c9d1c3-147d-4ba5-96c3-21ec80d036fb)

### Additional Information

- I will ready work on this project.
- please assign me....

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by AbhiPatel10** [comment]
Just Navigating to the gihub is not needed, we are planning to change the design of the project page.
