### ISSUE TITLE
[Feature] Add a Testimonial Page to the Website

### ISSUE THREAD

**Issue by Manav173** [AbhiPatel10/openzone#78]
### Description

I propose the addition of a Testimonial Page to our website. This page will serve as a centralized location for showcasing customer feedback and success stories.

I would be really thankful if you assign me this issue as a part of GSSoC'24 @AbhiPatel10  .

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by AbhiPatel10** [comment]
Not Planning to add testimonial section in this project.

@Manav173 Thanks for your enthusiasm.
