### ISSUE TITLE
[OTHER] Search page & search bar UI not responsive for mobile screens

### ISSUE THREAD

**Issue by SnehansuBehera** [AbhiPatel10/openzone#82]
### What would you like to share or ask?

The Search bar is overflowing outside the container and the the search page is not given proper alignment for mobile screens.

![Screenshot 2024-05-18 113744](https://github.com/AbhiPatel10/openzone/assets/121883802/2928263e-f9fb-41c0-9a67-6ad821f4ec7c)

### Additional information

@AbhiPatel10 could you please assign this issue to me, I would like to contribute to it under gssoc'24.

**Comment by Mastermind730** [comment]
@AbhiPatel10 please assign me this issue.I have good experience on working on Next js and tailwind and have also won a hackathon

**Comment by AbhiPatel10** [comment]
Someone Already working on this issue.

Thanks for your enthusiasm
