### ISSUE TITLE
Issue: Missing "Contact Us" Page

### ISSUE THREAD

**Issue by bro-maanii** [AbhiPatel10/openzone#83]
### Description

The website currently lacks a "Contact Us" page, which is essential for users to reach out for support, inquiries, or feedback.

### Additional Information

The lack of a "Contact Us" page hinders user communication and can lead to missed opportunities for user feedback, support requests, and inquiries. It may frustrate users who need assistance or have questions and cannot find a direct way to contact the team. Adding a "Contact Us" page enhances user experience and ensures open lines of communication between the users and the website administrators.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bro-maanii** [comment]
![image](https://github.com/AbhiPatel10/openzone/assets/125199246/68c5f2a4-7008-4f1c-b4f6-41716a31afd7)

just like this section

**Comment by AbhiPatel10** [comment]
Contact us page has been added. 

Thanks for your enthusiasm
