### ISSUE TITLE
[Feature] Signup/login page

### ISSUE THREAD

**Issue by Jagpreet153** [AbhiPatel10/openzone#85]
### Description

I would be adding a signup/login page in frontend  

### Screenshots

![Screenshot 2024-05-18 193650](https://github.com/AbhiPatel10/openzone/assets/119691733/ffbfcd8c-913a-4c5d-b487-54884e9c9144)

The user can choose signup/login option from navbar section

### Additional Information

Kindly assign this issue to me under GSSoC'24

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by AbhiPatel10** [comment]
We have a Connect with GitHub feature and i'm not planning to any additional sign in and signup method.
