### ISSUE TITLE
[Feature]: Adding github workflow Greetings.yaml

### ISSUE THREAD

**Issue by Ayesha-Siddiqua88** [AbhiPatel10/openzone#86]
### Description

The workflow greets whenever a contributor opens an issue.
@AbhiPatel10 , Please assign this to me so I can start working on it.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by AbhiPatel10** [comment]
Already added Greating Flow

Thanks for your enthusiasm for this project.
