### ISSUE TITLE
Add pages for "privacy policy and terms and conditions" matching website's design theme.

### ISSUE THREAD

**Issue by MastanSayyad** [AbhiPatel10/openzone#92]
### Description

Hey @AbhiPatel10 what about the pages for **privacy policy and terms and conditions**?? as the Openzone is related to opensource project contribution , it must have some terms and conditions users are liable too and policy to showcase and professionalism.

### Screenshots

![image](https://github.com/AbhiPatel10/openzone/assets/101971980/7fbfb863-f1ff-4a7c-9aa1-b97effd5b112)

### Additional Information

Could you please assign this issue to me under GSSOC 24?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by AbhiPatel10** [comment]
Assigning to you @Master Sayyad
