### ISSUE TITLE
[Bug] Search Request not triggering while clicking Enter

### ISSUE THREAD

**Issue by anujsingh4545** [AbhiPatel10/openzone#99]
### What would you like to share or ask?

# Description
- In projects Search Page, while searching something, the general behaviour should be, if user click enter or seach button in both cases search should trigger.
- But in this case clicking on search only triggering, search.
- This submit type is inefficent.

<img width="351" alt="image" src="https://github.com/AbhiPatel10/openzone/assets/76861751/d9516669-6945-4c88-8d30-f4b33daa2288">

### Additional information

- Update : Already working into this issue.
- Note : I'm not gssoc contributor, so tags are not needed.

**Comment by AbhiPatel10** [comment]
> ### What would you like to share or ask?
> 
> # Description
> - In projects Search Page, while searching something, the general behaviour should be, if user click enter or seach button in both cases search should trigger.
> - But in this case clicking on search only triggering, search.
> - This submit type is inefficent.
> 
> <img width="351" alt="image" src="https://github.com/AbhiPatel10/openzone/assets/76861751/d9516669-6945-4c88-8d30-f4b33daa2288">
> 
> 
> ### Additional information
> 
> - Update : Already working into this issue.
> - Note : I'm not gssoc contributor, so tags are not needed.

Assigning to you @anujsingh4545 

Great to see the enthusiastic contributor.
